# File: /multi_agent_system/docker-compose.yml
version: '3.8'

services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: always

  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      GOOGLE_API_KEY: ${GOOGLE_API_KEY}
      REDIS_HOST: redis # ADDED THIS LINE: Tells the app how to find Redis
    volumes:
      # Mount the current directory (your project) into the container's /app
      # This allows changes to code/samples to be reflected without rebuilding image (for development)
      - .:/app
    depends_on:
      - redis
    env_file:
      - ./.env # This loads GOOGLE_API_KEY and any other necessary env vars
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload # --reload for development

volumes:
  redis_data: